version: '3.8'


services:
  app:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:latest
#    environment:
#      - POSTGRES_PASSWORD=e!_sUltan747
    ports:
      - 5432:5432